const positions = {
  1: { type: 'free' },
  2: {
    type: 'build',
    name: 'galanteya',
    owner: null,
    costBuy: 600,
    costSell: 300,
    costParking: 250,
  },
  3: { type: 'bonus', sign: 'random' },
  4: {
    type: 'build',
    name: 'makey',
    owner: null,
    costBuy: 600,
    costSell: 300,
    costParking: 250,
  },
  5: { type: 'bonus', sign: 'plus' },
  6: {
    type: 'build',
    name: 'belshina',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 1500,
  },
  7: {
    type: 'build',
    name: 'milavitsa',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 350,
  },
  8: { type: 'bonus', sign: 'random' },
  9: {
    type: 'build',
    name: 'markformelle',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 400,
  },
  10: {
    type: 'build',
    name: 'svitanak',
    owner: null,
    costBuy: 1200,
    costSell: 600,
    costParking: 450,
  },
  11: { type: 'bonus', sign: 'minus' },
  12: {
    type: 'build',
    name: 'kommunarka',
    owner: null,
    costBuy: 1400,
    costSell: 700,
    costParking: 500,
  },
  13: {
    type: 'build',
    name: 'horizont',
    owner: null,
    costBuy: 1500,
    costSell: 750,
    costParking: 750,
  },
  14: {
    type: 'build',
    name: 'spartak',
    owner: null,
    costBuy: 1400,
    costSell: 700,
    costParking: 550,
  },
  15: {
    type: 'build',
    name: 'readeater',
    owner: null,
    costBuy: 1600,
    costSell: 500,
    costParking: 600,
  },
  16: {
    type: 'build',
    name: 'maz',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 1500,
  },
  17: {
    type: 'build',
    name: 'lidskaye',
    owner: null,
    costBuy: 1800,
    costSell: 900,
    costParking: 750,
  },
  18: { type: 'bonus', sign: 'random' },
  19: {
    type: 'build',
    name: 'alivarya',
    owner: null,
    costBuy: 1800,
    costSell: 900,
    costParking: 800,
  },
  20: {
    type: 'build',
    name: 'kristall',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 850,
  },
  21: {},
  22: {
    type: 'build',
    name: 'belita',
    owner: null,
    costBuy: 2200,
    costSell: 1100,
    costParking: 1000,
  },
  23: { type: 'bonus', sign: 'random' },
  24: {
    type: 'build',
    name: 'relodis',
    owner: null,
    costBuy: 2200,
    costSell: 1100,
    costParking: 1100,
  },
  25: {
    type: 'build',
    name: 'luxvisage',
    owner: null,
    costBuy: 2400,
    costSell: 1200,
    costParking: 1200,
  },
  26: {
    type: 'build',
    name: 'belaz',
    owner: null,
    costBuy: 2000,
    costSell: 100,
    costParking: 1500,
  },
  27: {
    type: 'build',
    name: 'aist',
    owner: null,
    costBuy: 2600,
    costSell: 1800,
    costParking: 1300,
  },
  28: {
    type: 'build',
    name: 'krakken',
    owner: null,
    costBuy: 2600,
    costSell: 1800,
    costParking: 1400,
  },
  29: {
    type: 'build',
    name: 'atlant',
    owner: null,
    costBuy: 1500,
    costSell: 750,
    costParking: 750,
  },
  30: {
    type: 'build',
    name: 'minsk',
    owner: null,
    costBuy: 2800,
    costSell: 1900,
    costParking: 1500,
  },
  31: { type: 'bonus', sign: 'minus' },
  32: {
    type: 'build',
    name: 'shagovita',
    owner: null,
    costBuy: 3000,
    costSell: 1500,
    costParking: 1600,
  },
  33: {
    type: 'build',
    name: 'belwest',
    owner: null,
    costBuy: 3000,
    costSell: 1500,
    costParking: 1750,
  },
  34: { type: 'bonus', sign: 'random' },
  35: {
    type: 'build',
    name: 'marko',
    owner: null,
    costBuy: 3200,
    costSell: 1600,
    costParking: 1900,
  },
  36: {
    type: 'build',
    name: 'belarus',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 1500,
  },
  37: { type: 'bonus', sign: 'plus' },
  38: {
    type: 'build',
    name: 'bmz',
    owner: null,
    costBuy: 3500,
    costSell: 1750,
    costParking: 450,
  },
  39: { type: 'bonus', sign: 'random' },
  40: {
    type: 'build',
    name: 'belaruskali',
    owner: null,
    costBuy: 4000,
    costSell: 2000,
    costParking: 2250,
  },
};

module.exports = positions;
