// eslint-disable-next-line import/prefer-default-export
export const allCells = [
  { id: 1 },
  {
    id: 2,
    type: 'build',
    name: 'galanteya',
    company: 'Galanteya',
    owner: null,
    costBuy: 600,
    costSell: 300,
    costParking: 250,
    row: 'top',
  },
  { id: 3 },
  {
    id: 4,
    type: 'build',
    name: 'makey',
    company: 'Makey',
    owner: null,
    costBuy: 600,
    costSell: 300,
    costParking: 250,
    row: 'top',
  },
  { id: 5 },
  {
    id: 6,
    type: 'build',
    name: 'belshina',
    company: 'Belshina',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 1500,
    row: 'top',
  },
  {
    id: 7,
    type: 'build',
    name: 'milavitsa',
    company: 'Milavitsa',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 350,
    row: 'top',
  },
  { id: 8 },
  {
    id: 9,
    type: 'build',
    name: 'markformelle',
    company: 'MarkFormelle',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 400,
    row: 'top',
  },
  {
    id: 10,
    type: 'build',
    name: 'svitanak',
    company: 'Svitanak',
    owner: null,
    costBuy: 1200,
    costSell: 600,
    costParking: 450,
    row: 'top',
  },
  { id: 11 },
  {
    id: 12,
    type: 'build',
    name: 'kommunarka',
    company: 'Kommunarka',
    owner: null,
    costBuy: 1400,
    costSell: 700,
    costParking: 500,
    row: 'right',
  },
  {
    id: 13,
    type: 'build',
    name: 'horizont',
    company: 'Horizont',
    owner: null,
    costBuy: 1500,
    costSell: 750,
    costParking: 750,
    row: 'right',
  },
  {
    id: 14,
    type: 'build',
    name: 'spartak',
    company: 'Spartak',
    owner: null,
    costBuy: 1400,
    costSell: 700,
    costParking: 550,
    row: 'right',
  },
  {
    id: 15,
    type: 'build',
    name: 'readeater',
    company: 'Krasny Pischevik',
    owner: null,
    costBuy: 1600,
    costSell: 500,
    costParking: 600,
    row: 'right',
  },
  {
    id: 16,
    type: 'build',
    name: 'maz',
    company: 'Maz',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 1500,
    row: 'right',
  },
  {
    id: 17,
    type: 'build',
    name: 'lidskaye',
    company: 'Lidskaye',
    owner: null,
    costBuy: 1800,
    costSell: 900,
    costParking: 750,
    row: 'right',
  },
  { id: 18 },
  {
    id: 19,
    type: 'build',
    name: 'alivarya',
    company: 'Alivaria',
    owner: null,
    costBuy: 1800,
    costSell: 900,
    costParking: 800,
    row: 'right',
  },
  {
    id: 20,
    type: 'build',
    name: 'kristall',
    company: 'Kristall',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 850,
    row: 'right',
  },
  { id: 21 },
  {
    id: 22,
    type: 'build',
    name: 'belita',
    company: 'Belita-Vitex',
    owner: null,
    costBuy: 2200,
    costSell: 1100,
    costParking: 1000,
    row: 'bottom',
  },
  { id: 23 },
  {
    id: 24,
    type: 'build',
    name: 'relodis',
    company: 'Relodis',
    owner: null,
    costBuy: 2200,
    costSell: 1100,
    costParking: 1100,
    row: 'bottom',
  },
  {
    id: 25,
    type: 'build',
    name: 'luxvisage',
    company: 'Luxvisage',
    owner: null,
    costBuy: 2400,
    costSell: 1200,
    costParking: 1200,
    row: 'bottom',
  },
  {
    id: 26,
    type: 'build',
    name: 'belaz',
    company: 'Belaz',
    owner: null,
    costBuy: 2000,
    costSell: 100,
    costParking: 1500,
    row: 'bottom',
  },
  {
    id: 27,
    type: 'build',
    name: 'aist',
    company: 'Aist',
    owner: null,
    costBuy: 2600,
    costSell: 1800,
    costParking: 1300,
    row: 'bottom',
  },
  {
    id: 28,
    type: 'build',
    name: 'krakken',
    company: 'Krakken',
    owner: null,
    costBuy: 2600,
    costSell: 1800,
    costParking: 1400,
    row: 'bottom',
  },
  {
    id: 29,
    type: 'build',
    name: 'atlant',
    company: 'Atlant',
    owner: null,
    costBuy: 1500,
    costSell: 750,
    costParking: 750,
    row: 'bottom',
  },
  {
    id: 30,
    type: 'build',
    name: 'minsk',
    company: 'Minsk',
    owner: null,
    costBuy: 2800,
    costSell: 1900,
    costParking: 1500,
    row: 'bottom',
  },
  { id: 31 },
  {
    id: 32,
    type: 'build',
    name: 'shagovita',
    company: 'Shagovita',
    owner: null,
    costBuy: 3000,
    costSell: 1500,
    costParking: 1600,
    row: 'left',
  },
  {
    id: 33,
    type: 'build',
    name: 'belwest',
    company: 'Belwest',
    owner: null,
    costBuy: 3000,
    costSell: 1500,
    costParking: 1750,
    row: 'left',
  },
  { id: 34 },
  {
    id: 35,
    type: 'build',
    name: 'marko',
    company: 'Marko',
    owner: null,
    costBuy: 3200,
    costSell: 1600,
    costParking: 1900,
    row: 'left',
  },
  {
    id: 36,
    type: 'build',
    name: 'belarus',
    company: 'Belarus',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 1500,
    row: 'left',
  },
  { id: 37 },
  {
    id: 38,
    type: 'build',
    name: 'bmz',
    company: 'Bmz',
    owner: null,
    costBuy: 3500,
    costSell: 1750,
    costParking: 2250,
    row: 'left',
  },
  { id: 39 },
  {
    id: 40,
    type: 'build',
    name: 'belaruskali',
    company: 'Belaruskali',
    owner: null,
    costBuy: 4000,
    costSell: 2000,
    costParking: 2500,
    row: 'left',
  },
];
