// eslint-disable-next-line import/prefer-default-export
export const allCells = [
  { id: 1 },
  {
    id: 2,
    type: 'build',
    name: 'galanteya',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 3 },
  {
    id: 4,
    type: 'build',
    name: 'makey',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 5 },
  {
    id: 6,
    type: 'build',
    name: 'belshina',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 7,
    type: 'build',
    name: 'milavitsa',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 8 },
  {
    id: 9,
    type: 'build',
    name: 'markformelle',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 10,
    type: 'build',
    name: 'svitanak',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 11 },
  {
    id: 12,
    type: 'build',
    name: 'kommunarka',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 13,
    type: 'build',
    name: 'horizont',
    owner: null,
    costBuy: 1000,
    costSell: 500,
  },
  {
    id: 14,
    type: 'build',
    name: 'spartak',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 15,
    type: 'build',
    name: 'krasnyi',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 16,
    type: 'build',
    name: 'maz',
    owner: null,
    costBuy: 1000,
    costSell: 500,
  },
  {
    id: 17,
    type: 'build',
    name: 'lidskaye',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 18 },
  {
    id: 19,
    type: 'build',
    name: 'alivarya',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 20,
    type: 'build',
    name: 'kristall',
    owner: null,
    costBuy: 1000,
    costSell: 500,
  },
  { id: 21 },
  {
    id: 22,
    type: 'build',
    name: 'belita',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 23 },
  {
    id: 24,
    type: 'build',
    name: 'relodis',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 25,
    type: 'build',
    name: 'luxvisage',
    owner: null,
    costBuy: 1000,
    costSell: 500,
  },
  {
    id: 26,
    type: 'build',
    name: 'belaz',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 27,
    type: 'build',
    name: 'aist',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 28,
    type: 'build',
    name: 'krakken',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 29,
    type: 'build',
    name: 'atlant',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 30,
    type: 'build',
    name: 'minsk',
    owner: null,
    costBuy: 1000,
    costSell: 500,
  },
  { id: 31 },
  {
    id: 32,
    type: 'build',
    name: 'shagovita',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 33,
    type: 'build',
    name: 'belwest',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 34 },
  {
    id: 35,
    type: 'build',
    name: 'marko',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  {
    id: 36,
    type: 'build',
    name: 'belarus',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 37 },
  {
    id: 38,
    type: 'build',
    name: 'bmz',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
  { id: 39 },
  {
    id: 40,
    type: 'build',
    name: 'belaruskali',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 1000,
  },
];
