// eslint-disable-next-line import/prefer-default-export
export const allCells = [
  { id: 1 },
  {
    id: 2,
    type: 'build',
    name: 'galanteya',
    owner: null,
    costBuy: 600,
    costSell: 300,
    costParking: 50,
    row: 'top',
  },
  { id: 3 },
  {
    id: 4,
    type: 'build',
    name: 'makey',
    owner: null,
    costBuy: 600,
    costSell: 300,
    costParking: 50,
    row: 'top',
  },
  { id: 5 },
  {
    id: 6,
    type: 'build',
    name: 'belshina',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 300,
    row: 'top',
  },
  {
    id: 7,
    type: 'build',
    name: 'milavitsa',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 70,
    row: 'top',
  },
  { id: 8 },
  {
    id: 9,
    type: 'build',
    name: 'markformelle',
    owner: null,
    costBuy: 1000,
    costSell: 500,
    costParking: 80,
    row: 'top',
  },
  {
    id: 10,
    type: 'build',
    name: 'svitanak',
    owner: null,
    costBuy: 1200,
    costSell: 600,
    costParking: 90,
    row: 'top',
  },
  { id: 11 },
  {
    id: 12,
    type: 'build',
    name: 'kommunarka',
    owner: null,
    costBuy: 1400,
    costSell: 700,
    costParking: 100,
    row: 'right',
  },
  {
    id: 13,
    type: 'build',
    name: 'horizont',
    owner: null,
    costBuy: 1500,
    costSell: 750,
    costParking: 150,
    row: 'right',
  },
  {
    id: 14,
    type: 'build',
    name: 'spartak',
    owner: null,
    costBuy: 1400,
    costSell: 700,
    costParking: 110,
    row: 'right',
  },
  {
    id: 15,
    type: 'build',
    name: 'readeater',
    owner: null,
    costBuy: 1600,
    costSell: 500,
    costParking: 120,
    row: 'right',
  },
  {
    id: 16,
    type: 'build',
    name: 'maz',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 300,
    row: 'right',
  },
  {
    id: 17,
    type: 'build',
    name: 'lidskaye',
    owner: null,
    costBuy: 1800,
    costSell: 900,
    costParking: 150,
    row: 'right',
  },
  { id: 18 },
  {
    id: 19,
    type: 'build',
    name: 'alivarya',
    owner: null,
    costBuy: 1800,
    costSell: 900,
    costParking: 160,
    row: 'right',
  },
  {
    id: 20,
    type: 'build',
    name: 'kristall',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 170,
    row: 'right',
  },
  { id: 21 },
  {
    id: 22,
    type: 'build',
    name: 'belita',
    owner: null,
    costBuy: 2200,
    costSell: 1100,
    costParking: 200,
    row: 'bottom',
  },
  { id: 23 },
  {
    id: 24,
    type: 'build',
    name: 'relodis',
    owner: null,
    costBuy: 2200,
    costSell: 1100,
    costParking: 220,
    row: 'bottom',
  },
  {
    id: 25,
    type: 'build',
    name: 'luxvisage',
    owner: null,
    costBuy: 2400,
    costSell: 1200,
    costParking: 240,
    row: 'bottom',
  },
  {
    id: 26,
    type: 'build',
    name: 'belaz',
    owner: null,
    costBuy: 2000,
    costSell: 100,
    costParking: 300,
    row: 'bottom',
  },
  {
    id: 27,
    type: 'build',
    name: 'aist',
    owner: null,
    costBuy: 2600,
    costSell: 1800,
    costParking: 260,
    row: 'bottom',
  },
  {
    id: 28,
    type: 'build',
    name: 'krakken',
    owner: null,
    costBuy: 2600,
    costSell: 1800,
    costParking: 280,
    row: 'bottom',
  },
  {
    id: 29,
    type: 'build',
    name: 'atlant',
    owner: null,
    costBuy: 1500,
    costSell: 750,
    costParking: 150,
    row: 'bottom',
  },
  {
    id: 30,
    type: 'build',
    name: 'minsk',
    owner: null,
    costBuy: 2800,
    costSell: 1900,
    costParking: 300,
    row: 'bottom',
  },
  { id: 31 },
  {
    id: 32,
    type: 'build',
    name: 'shagovita',
    owner: null,
    costBuy: 3000,
    costSell: 1500,
    costParking: 320,
    row: 'left',
  },
  {
    id: 33,
    type: 'build',
    name: 'belwest',
    owner: null,
    costBuy: 3000,
    costSell: 1500,
    costParking: 350,
    row: 'left',
  },
  { id: 34 },
  {
    id: 35,
    type: 'build',
    name: 'marko',
    owner: null,
    costBuy: 3200,
    costSell: 1600,
    costParking: 380,
    row: 'left',
  },
  {
    id: 36,
    type: 'build',
    name: 'belarus',
    owner: null,
    costBuy: 2000,
    costSell: 1000,
    costParking: 300,
    row: 'left',
  },
  { id: 37 },
  {
    id: 38,
    type: 'build',
    name: 'bmz',
    owner: null,
    costBuy: 3500,
    costSell: 1750,
    costParking: 450,
    row: 'left',
  },
  { id: 39 },
  {
    id: 40,
    type: 'build',
    name: 'belaruskali',
    owner: null,
    costBuy: 4000,
    costSell: 2000,
    costParking: 500,
    row: 'left',
  },
];
